---
  - name: "Installing Libraries"
    sudo: yes
    sudo_user: root
    apt: pkg={{item}} update_cache=yes state=latest
    with_items:
      - libsnappy-dev
      - libcppunit-dev
      - liblzo2-dev
      - protobuf-compiler
      - subversion
      - autoconf
      - automake
      - libz-dev
      - sharutils
      - libfuse-dev
      - libssl-dev
      - build-essential 
      - dh-make 
      - debhelper 
      - devscripts
      - asciidoc
