---    
 host_label: jenkins_slaves
 maven_version: 3.2.1
 ant_version: 1.9.4
 forrest_version: 0.9
 maven_url: http://mirror.nexcess.net/apache/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz
 ant_url: http://www.dsgnwrld.com/am//ant/binaries/apache-ant-{{ant_version}}-bin.tar.gz
 forrest_url: http://psg.mtu.edu/pub/apache/forrest/apache-forrest-{{forrest_version}}-sources.tar.gz
 jenkins_user: jenkins
 jenkins_home: "/home/{{jenkins_user}}"
 tools_home: "{{jenkins_home}}/tools"
 maven_home: "{{tools_home}}/maven"
 ant_home: "{{tools_home}}/ant"
 forrest_home: "{{tools_home}}/forrest"
 m2_cache_dir: "{{jenkins_home}}/.m2"
 ssh_dir: "{{jenkins_home}}/.ssh"
